security:
  oauth2:
    client:
      clientId: 2356064664682874
      clientSecret: 003b5323bbd07513872c2117ec075518
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
